# Generated by Django 3.2.16 on 2022-10-26 09:37

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_priority', models.IntegerField(default=50, verbose_name='Category priority')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Languages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=50, verbose_name='Language')),
            ],
            options={
                'verbose_name': 'Language',
                'verbose_name_plural': 'Languages',
            },
        ),
        migrations.CreateModel(
            name='Stories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hide_in_stories', models.BooleanField(default=False, verbose_name='Hide in stories')),
                ('post_priority', models.IntegerField(default=20, verbose_name='Post priority')),
                ('fresh_after', models.DateField(verbose_name='Fresh after')),
                ('fresh_before', models.DateField(verbose_name='Fresh before')),
                ('clients_eligible', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=[2], size=None)),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='story_categories', to='main_app.categories', verbose_name='Category id')),
            ],
            options={
                'verbose_name': 'Story',
                'verbose_name_plural': 'Stories',
            },
        ),
        migrations.CreateModel(
            name='Stories_i18n',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Title')),
                ('subtitle', models.CharField(max_length=500, verbose_name='Subtitle')),
                ('title_icon', models.CharField(max_length=300, verbose_name='Title icon')),
                ('title_image', models.CharField(max_length=300, verbose_name='Title image')),
                ('language_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main_app.languages', verbose_name='Language id')),
                ('story_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main_app.stories', verbose_name='Story id')),
            ],
            options={
                'verbose_name': 'Story_i18n',
                'verbose_name_plural': 'Stories_i18n',
            },
        ),
        migrations.CreateModel(
            name='Pages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(max_length=300, verbose_name='Image')),
                ('icon', models.CharField(default='assets/icon/icon_startscreen_new.svg', max_length=300, verbose_name='Icon')),
                ('headline', models.CharField(max_length=500, verbose_name='Headline')),
                ('text', models.TextField(verbose_name='Text')),
                ('deleted', models.BooleanField(default=False, verbose_name='Deleted')),
                ('story_i18n_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pages', to='main_app.stories_i18n', verbose_name='Story_i18n id')),
            ],
            options={
                'verbose_name': 'Page',
                'verbose_name_plural': 'Pages',
            },
        ),
        migrations.CreateModel(
            name='Categories_i18n',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='News', max_length=500, verbose_name='Category')),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main_app.categories', verbose_name='Category id')),
                ('language_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main_app.languages', verbose_name='Language id')),
            ],
            options={
                'verbose_name': 'Category_i18n',
                'verbose_name_plural': 'Categories_i18n',
            },
        ),
    ]
