# Generated by Django 3.2.16 on 2022-11-10 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categories_i18n',
            old_name='language_id',
            new_name='language',
        ),
        migrations.RenameField(
            model_name='stories_i18n',
            old_name='language_id',
            new_name='language',
        ),
        migrations.RemoveField(
            model_name='categories_i18n',
            name='category_id',
        ),
        migrations.RemoveField(
            model_name='pages',
            name='story_i18n_id',
        ),
        migrations.RemoveField(
            model_name='stories',
            name='category_id',
        ),
        migrations.RemoveField(
            model_name='stories_i18n',
            name='story_id',
        ),
        migrations.AddField(
            model_name='categories_i18n',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='categoriesi18n_categories', to='main_app.categories', verbose_name='Category id'),
        ),
        migrations.AddField(
            model_name='pages',
            name='story_i18n',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='pages_storiesi18n', to='main_app.stories_i18n', verbose_name='Story_i18n id'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stories',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='stories_categories', to='main_app.categories', verbose_name='Category id'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stories_i18n',
            name='story',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='storiesi18n_stories', to='main_app.stories', verbose_name='Story id'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='stories',
            name='hide_in_stories',
            field=models.BooleanField(default=True, verbose_name='Hide in stories'),
        ),
        migrations.AlterField(
            model_name='stories_i18n',
            name='title_icon',
            field=models.CharField(max_length=500, verbose_name='Title icon'),
        ),
        migrations.AlterField(
            model_name='stories_i18n',
            name='title_image',
            field=models.CharField(max_length=500, verbose_name='Title image'),
        ),
    ]
